---
#------------------------------------------------------------------------------
#  
# Playbook for 201 Automation Workshop - Runs AFTER Terraform has built Infra.
#
#------------------------------------------------------------------------------
#   Terraform should create/populate the inventory file ../inventory/bigips.ini
#   To use this 'static inventory':
#     Run 'ansible-playbook ./main.yaml -i ../inventory/bigips.ini --ask-vault-pass'
#   Or you can use the aws_ec2 'dynamic inventory' plugin, in which case:
#     Run 'ansible-playbook ./main.yaml -i ../inventory/aws_ec2.yaml --ask-vault-pass'
#------------------------------------------------------------------------------

- name: CONFIGURE DEPLOYED BIG-IP
  hosts: bigips
  
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    #AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------

  vars_files:

    - ../../../../../creds/aws-creds.yaml
    - ../../../../../creds/big-creds.yaml
    - ../vars/vars.yaml
    - ../vars/id.yaml    

  
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------

  tasks:

#  - include_tasks: ../tasks/tasks-01-deploy-juice-app-ec2.yaml
  - include_tasks: ../tasks/tasks-01a-deploy-juice-app-ec2-non-docker.yaml
  - include_tasks: ../tasks/tasks-02-aws-dynamic-eni-ips.yaml
  - include_tasks: ../tasks/tasks-03-deploy-do.yaml
  - include_tasks: ../tasks/tasks-04-deploy-ts.yaml
  - include_tasks: ../tasks/tasks-05-deploy-as3.yaml
  - include_tasks: ../tasks/tasks-06-outputs.yaml

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...