---
#------------------------------------------------------------------------------
# Playbook to DELETE Ansible Components.
#
#   Requires pyvmomi python library
#------------------------------------------------------------------------------

- name: DESTROY DEPLOYMEMT
  hosts: bigips
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_SESSION_TOKEN: "{{ aws_session_token }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------

  vars_files:

    - ../../../../../creds/aws-creds.yaml
    - ../vars/vars.yaml
    - ../vars/id.yaml    

  
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------

  tasks:

  - include_tasks: ../tasks/tasks-11-remove-aws-dynamic-eni-ips.yaml

#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...